spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:20}

logging:
  structured:
    format:
      console: ecs
  level:
    root: INFO
    com.stockhub: INFO

springdoc:
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}
